data_loader:
  events: 'C:\Users\DataRetail\events.csv'
  category_tree: 'C:\Users\DataRetail\category_tree.csv'
  item_properties_part1: 'C:\Users\DataRetail\item_properties_part1.csv'
  item_properties_part2: 'C:\Users\DataRetail\item_properties_part2.csv'