data_loader:
  events: 'C:\Users\DataRetail\events.csv'
  category_tree: 'C:\Users\DataRetail\category_tree.csv'
  item_properties_part1: 'C:\Users\DataRetail\item_properties_part1.csv'
  item_properties_part2: 'C:\Users\DataRetail\item_properties_part2.csv'
data_preparation:
  session_duration: 1800
  visitor_features:
    thold_max_views_per_minute: 10
    thold_repetitive_action: 5
model:
  anomaly_detection:
    features:
    isolation_forest:
      params:
        n_estimators: [100, 200]
        max_samples: ['auto']
        contamination: ['auto']
        max_features: [1.0]
        bootstrap: [False]
        n_jobs: [-1]
        random_state: [42]
        verbose: [0]
        warm_start: [False]