data_loader:
  events: 'C:\Users\gonpr\Downloads\events.csv'
  category_tree: 'C:\Users\gonpr\Downloads\category_tree.csv'
  item_properties_part1: 'C:\Users\gonpr\Downloads\item_properties_part1.csv'
  item_properties_part2: 'C:\Users\gonpr\Downloads\item_properties_part2.csv'
data_preparation:
  session_duration: 1800
features:
  visitor: '../src/data/queries/visitor_features.sql'
  item: '../src/data/queries/item_features.sql'
model:
  anomaly_detection:
    features:
    isolation_forest:
      params:
        n_estimators: [10, 50]
        max_samples: ['auto']
        contamination: ['auto']
        max_features: [1.0]
        bootstrap: [False]
        n_jobs: [-1]
        random_state: [42]
        verbose: [0]
        warm_start: [False]
    hdbscan:
      params:
        min_cluster_size: [1000, 2000, 4000]
        min_samples: [38]